var target = args[0];
var t_script = args[1];
var script = "/scripts/" + t_script;

scp(t_script, getHostname(), target);
connect(target);
run("NUKE.exe");

// Get memory usage of script
var mem_usage = getScriptRam(script, target);
var server_max = getServerMaxRam();
var server_current = getServerUsedRam();

// Run main script with full memory usage
var  thread_number = (server_max - server_current) % mem_usage;
run(script, thread_number);